"""contact submission

Revision ID: 630653227996
Revises: 8c1b7a6f6d89
Create Date: 2024-03-01 11:24:11.118016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630653227996'
down_revision = '8c1b7a6f6d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_submission')
    # ### end Alembic commands ###
