"""initial migration

Revision ID: 8c1b7a6f6d89
Revises: 
Create Date: 2024-02-24 16:28:36.512092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1b7a6f6d89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.Column('ProductName', sa.String(length=100), nullable=False),
    sa.Column('Color', sa.String(length=40), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=False),
    sa.Column('LastBought', sa.DateTime(), nullable=True),
    sa.Column('ImageUrl', sa.String(length=100), nullable=False),
    sa.Column('Rating', sa.Float(), nullable=False),
    sa.Column('RatingCount', sa.Integer(), nullable=False),
    sa.Column('CategoryName', sa.String(length=40), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('Products')
    # ### end Alembic commands ###
